# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jeremynguyen/Documents/GitHub/particlePhysics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jeremynguyen/Documents/GitHub/particlePhysics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jeremynguyen/Documents/GitHub/particlePhysics/CMakeFiles /Users/jeremynguyen/Documents/GitHub/particlePhysics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jeremynguyen/Documents/GitHub/particlePhysics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named particlePhysics

# Build rule for target.
particlePhysics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 particlePhysics
.PHONY : particlePhysics

# fast build rule for target.
particlePhysics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/build
.PHONY : particlePhysics/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/main.cpp.s
.PHONY : main.cpp.s

sources/circleParticle.o: sources/circleParticle.cpp.o
.PHONY : sources/circleParticle.o

# target to build an object file
sources/circleParticle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/circleParticle.cpp.o
.PHONY : sources/circleParticle.cpp.o

sources/circleParticle.i: sources/circleParticle.cpp.i
.PHONY : sources/circleParticle.i

# target to preprocess a source file
sources/circleParticle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/circleParticle.cpp.i
.PHONY : sources/circleParticle.cpp.i

sources/circleParticle.s: sources/circleParticle.cpp.s
.PHONY : sources/circleParticle.s

# target to generate assembly for a file
sources/circleParticle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/circleParticle.cpp.s
.PHONY : sources/circleParticle.cpp.s

sources/collisions.o: sources/collisions.cpp.o
.PHONY : sources/collisions.o

# target to build an object file
sources/collisions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/collisions.cpp.o
.PHONY : sources/collisions.cpp.o

sources/collisions.i: sources/collisions.cpp.i
.PHONY : sources/collisions.i

# target to preprocess a source file
sources/collisions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/collisions.cpp.i
.PHONY : sources/collisions.cpp.i

sources/collisions.s: sources/collisions.cpp.s
.PHONY : sources/collisions.s

# target to generate assembly for a file
sources/collisions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/collisions.cpp.s
.PHONY : sources/collisions.cpp.s

sources/particle.o: sources/particle.cpp.o
.PHONY : sources/particle.o

# target to build an object file
sources/particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/particle.cpp.o
.PHONY : sources/particle.cpp.o

sources/particle.i: sources/particle.cpp.i
.PHONY : sources/particle.i

# target to preprocess a source file
sources/particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/particle.cpp.i
.PHONY : sources/particle.cpp.i

sources/particle.s: sources/particle.cpp.s
.PHONY : sources/particle.s

# target to generate assembly for a file
sources/particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/particle.cpp.s
.PHONY : sources/particle.cpp.s

sources/squareParticle.o: sources/squareParticle.cpp.o
.PHONY : sources/squareParticle.o

# target to build an object file
sources/squareParticle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/squareParticle.cpp.o
.PHONY : sources/squareParticle.cpp.o

sources/squareParticle.i: sources/squareParticle.cpp.i
.PHONY : sources/squareParticle.i

# target to preprocess a source file
sources/squareParticle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/squareParticle.cpp.i
.PHONY : sources/squareParticle.cpp.i

sources/squareParticle.s: sources/squareParticle.cpp.s
.PHONY : sources/squareParticle.s

# target to generate assembly for a file
sources/squareParticle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/particlePhysics.dir/build.make CMakeFiles/particlePhysics.dir/sources/squareParticle.cpp.s
.PHONY : sources/squareParticle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... particlePhysics"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sources/circleParticle.o"
	@echo "... sources/circleParticle.i"
	@echo "... sources/circleParticle.s"
	@echo "... sources/collisions.o"
	@echo "... sources/collisions.i"
	@echo "... sources/collisions.s"
	@echo "... sources/particle.o"
	@echo "... sources/particle.i"
	@echo "... sources/particle.s"
	@echo "... sources/squareParticle.o"
	@echo "... sources/squareParticle.i"
	@echo "... sources/squareParticle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

